export const COLLATERAL_ASSETS = {
  USDC: {
    label: 'USD Coin',
    symbol: 'USDC',
    icon: '◎',
    color: '#2775ca',
    network: 'ethereum',
    maxLTV: 80,
    marginCallLTV: 85,
    liquidationLTV: 90,
    volMultiplier: 1.0,
    isStable: true,
  },
  USDT: {
    label: 'Tether',
    symbol: 'USDT',
    icon: '₮',
    color: '#26a17b',
    network: 'tron',
    maxLTV: 80,
    marginCallLTV: 85,
    liquidationLTV: 90,
    volMultiplier: 1.0,
    isStable: true,
  },
  cNGN: {
    label: 'cNGN Stablecoin',
    symbol: 'cNGN',
    icon: '₦',
    color: '#00d4a1',
    network: 'ethereum',
    maxLTV: 100,
    marginCallLTV: 102,
    liquidationLTV: 105,
    volMultiplier: 0.5,
    isStable: true,
  },
  BTC: {
    label: 'Bitcoin',
    symbol: 'BTC',
    icon: '₿',
    color: '#f7931a',
    network: 'bitcoin',
    maxLTV: 70,
    marginCallLTV: 75,
    liquidationLTV: 82,
    volMultiplier: 1.4,
    isStable: false,
  },
  ETH: {
    label: 'Ethereum',
    symbol: 'ETH',
    icon: 'Ξ',
    color: '#627eea',
    network: 'ethereum',
    maxLTV: 60,
    marginCallLTV: 70,
    liquidationLTV: 78,
    volMultiplier: 1.3,
    isStable: false,
  },
  SOL: {
    label: 'Solana',
    symbol: 'SOL',
    icon: '◎',
    color: '#9945ff',
    network: 'solana',
    maxLTV: 60,
    marginCallLTV: 68,
    liquidationLTV: 76,
    volMultiplier: 1.5,
    isStable: false,
  },
  XRP: {
    label: 'XRP',
    symbol: 'XRP',
    icon: '✕',
    color: '#346aa9',
    network: 'xrp',
    maxLTV: 60,
    marginCallLTV: 68,
    liquidationLTV: 76,
    volMultiplier: 1.4,
    isStable: false,
  },
  BNB: {
    label: 'BNB',
    symbol: 'BNB',
    icon: '◆',
    color: '#f3ba2f',
    network: 'bsc',
    maxLTV: 60,
    marginCallLTV: 68,
    liquidationLTV: 76,
    volMultiplier: 1.3,
    isStable: false,
  },
} as const;

export type CollateralAssetKey = keyof typeof COLLATERAL_ASSETS;
export type CollateralAsset = typeof COLLATERAL_ASSETS[CollateralAssetKey];
